repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        files: "^docs/.*\\.md"
  -   repo: https://github.com/nix-community/nixpkgs-fmt
      rev: v1.3.0
      hooks:
      -   id: nixpkgs-fmt
